version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      MYSQL_DATABASE: ucattu-db
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Set your MySQL/MariaDB host here
    ports:
      - "8080:80"  # You can change the host port as per your preference
    depends_on:
      - mysql
